- name: restart httpd
  service: name=httpd state=restarted enabled=yes

- name: restart mariadb
  service: name=mariadb state=restarted enabled=yes

- name: restart zabbix-server
  service: name=zabbix-server state=restarted enabled=yes

- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: restart snmptt
  service: name=snmptt state=restarted enabled=yes

- name: restart snmptrapd
  service: name=snmptrapd state=restarted enabled=yes

- name: restart chronyd
  service: name=chronyd state=restarted enabled=yes
